name: 'Anchor Test'
description: 'An "anchor test" action that runs in ~1 minute.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '16.15.1' # LTS
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '1.15.2' # stable
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.27.0' # latest
  features:
    description: 'Features to pass to cargo build-bpf'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: metadaoproject/setup-anchor@v1.1
      with:
        node-version: ${{ inputs.node-version }}
        solana-cli-version: ${{ inputs.solana-cli-version }}
        anchor-version: ${{ inputs.anchor-version }}
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules/
        key: node-modules-${{ runner.os }}-build-${{ inputs.node-version }}
    - name: Install node_modules
      run: yarn
      shell: bash
    - name: Create keypair
      run: solana-keygen new --no-bip39-passphrase
      shell: bash
    - name: Make Anchor.toml compatible with runner
      run: sed -i 's:/user/:/runner/:' Anchor.toml
      shell: bash
    - name: Install Cargo toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustc
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: anchor test -- --features ${{ inputs.features }}
      shell: bash
